# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from airhockey_main/ArmAngles.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class ArmAngles(genpy.Message):
  _md5sum = "03c786ea5bb5b9ff9771f16c1a88ee81"
  _type = "airhockey_main/ArmAngles"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float32 arm0_joint0
float32 arm0_joint1
float32 arm1_joint0
float32 arm1_joint1
bool success
"""
  __slots__ = ['arm0_joint0','arm0_joint1','arm1_joint0','arm1_joint1','success']
  _slot_types = ['float32','float32','float32','float32','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       arm0_joint0,arm0_joint1,arm1_joint0,arm1_joint1,success

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ArmAngles, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.arm0_joint0 is None:
        self.arm0_joint0 = 0.
      if self.arm0_joint1 is None:
        self.arm0_joint1 = 0.
      if self.arm1_joint0 is None:
        self.arm1_joint0 = 0.
      if self.arm1_joint1 is None:
        self.arm1_joint1 = 0.
      if self.success is None:
        self.success = False
    else:
      self.arm0_joint0 = 0.
      self.arm0_joint1 = 0.
      self.arm1_joint0 = 0.
      self.arm1_joint1 = 0.
      self.success = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4fB().pack(_x.arm0_joint0, _x.arm0_joint1, _x.arm1_joint0, _x.arm1_joint1, _x.success))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 17
      (_x.arm0_joint0, _x.arm0_joint1, _x.arm1_joint0, _x.arm1_joint1, _x.success,) = _get_struct_4fB().unpack(str[start:end])
      self.success = bool(self.success)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4fB().pack(_x.arm0_joint0, _x.arm0_joint1, _x.arm1_joint0, _x.arm1_joint1, _x.success))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 17
      (_x.arm0_joint0, _x.arm0_joint1, _x.arm1_joint0, _x.arm1_joint1, _x.success,) = _get_struct_4fB().unpack(str[start:end])
      self.success = bool(self.success)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4fB = None
def _get_struct_4fB():
    global _struct_4fB
    if _struct_4fB is None:
        _struct_4fB = struct.Struct("<4fB")
    return _struct_4fB
